/*
Copyright (c) 2025 Timur Gafarov.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module main;

import std.stdio;
import std.conv;
import std.file;
import std.string;

import bindbc.ktx;
import loader = bindbc.loader.sharedlib;
import vkformat;

void main()
{
    KTXSupport ktxVersion = loadKTX();
    writeln("KTX version: ", ktxVersion);
    
    if (loader.errors.length)
    {
        writeln("Loader errors:");
        foreach(info; loader.errors)
        {
            writeln(to!string(info.error), ": ", to!string(info.message));
        }
        
        return;
    }
    
    ktxTexture2* tex = null;
    KTX_error_code err = ktxTexture2_CreateFromNamedFile("data/test.ktx2",
        ktxTextureCreateFlagBits.KTX_TEXTURE_CREATE_LOAD_IMAGE_DATA_BIT, &tex);
    if (err != KTX_error_code.KTX_SUCCESS)
    {
        writeln(err);
        return;
    }
    
    writeln("vkFormat: ", cast(VkFormat)tex.vkFormat); // should be VK_FORMAT_UNDEFINED for Basis Universal
    writeln("supercompression scheme: ", tex.supercompressionScheme);

    bool needsTranscoding = ktxTexture2_NeedsTranscoding(tex);
    writeln("Needs transcoding: ", needsTranscoding);
    if (needsTranscoding)
    {
        // Transcode to DXT1
        ktx_transcode_fmt_e targetFormat = ktx_transcode_fmt_e.KTX_TTF_BC1_RGB;
        
        writeln("Transcoding...");
        err = ktxTexture2_TranscodeBasis(tex, targetFormat, 0);
        if (err != KTX_error_code.KTX_SUCCESS)
        {
            writeln(err);
            return;
        }
        
        writeln("Transcoded vkFormat: ", cast(VkFormat)tex.vkFormat);
    }
}
